### ISSUE TITLE
Making this gem independently operable

### ISSUE THREAD

**Issue by emiraydin** [danchoi/kindlerb#3]
Hi @danchoi, I wanted to ask before I proceed because this change would add a new dependency to the gem: What do you think about using the kindlegen gem (https://github.com/tdtds/kindlegen) to download kindlegen program and execute regardless of the system specific PATH variable? Making this gem independently operable would help a ton if anyone would use this gem when deploying to a PaaS such as Heroku. Also maybe adding a few more methods instead of just making it a one-run app would be good improvement as well. If you agree, I'll fork and make some changes accordingly.

**Comment by danchoi** [comment]
@emiraydin Thank you for the suggestion. I like the idea & added you as a collaborator to this repo. Please feel free to fork and then merge your changes. You can also add your name to the author section of the README.

**Comment by emiraydin** [comment]
I checked the kindlegen gem and it is a bit problematic. It doesn't work on Ruby versions below 2.0.0 and has some bugs. I think it would be smarter to write the download script from scratch instead. I'll get back to this later.

**Comment by danchoi** [comment]
OK

On Mon, Jan 12, 2015 at 02:07 AM, Emir Aydin <notifications@github.com> wrote:

> from: Emir Aydin <notifications@github.com>
> date: Sun, Jan 11 11:07 PM -08:00 2015
> to: danchoi/kindlerb <kindlerb@noreply.github.com>
> cc: Daniel Choi <dhchoi@gmail.com>
> reply-to: danchoi/kindlerb <reply@reply.github.com>
> subject: Re: [kindlerb] Making this gem independently operable (#3)
> 
> I checked the kindlegen gem and it is a bit problematic. It doesn't work on Ruby versions below 2.0.0 and has some bugs. I think it would be smarter to write the download script from scratch instead. I'll get back to this later.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/danchoi/kindlerb/issues/3#issuecomment-69535232

---
Sent from Vmail
http://danielchoi.com/software/vmail.html
